name: "${project.name}"
version: "${project.version}"
main: dev.anonymity.AnonymityPlugin
api-version: '1.21'
description: "Scrambled name, hidden skin, enchantment aura and obfuscated kill messages."
author: Anonymity
commands:
  fragment:
    description: Receive a Fragment Of Anonymity.
    usage: /fragment
    permission: anonymity.give
permissions:
  anonymity.use:
    description: Allows using the Fragment Of Anonymity to toggle anonymous mode.
    default: true
  anonymity.give:
    description: Allows giving yourself a Fragment Of Anonymity.
    default: op
